[package]
name = "notion-flows"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["lib", "cdylib"]

[dependencies]
http_req_wasi = "0.11.1"
notion-wasi = "0.5.1"
serde_json = "1.0.99"
